repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-ast
      - id: check-merge-conflict
      - id: check-added-large-files
        types: [ python ]

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.2.1
    hooks:
      - id: ruff-format
        exclude: ^alembic/, ^versions/
      - id: ruff
        exclude: ^alembic/, ^versions/
        args: [ --fix ]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.8.0
    hooks:
      - id: mypy
        exclude: ^alembic/, ^versions/
        additional_dependencies:
          - "pydantic"
