services:
  db:
    image: postgres:16.1
    container_name: db
    restart: always
    env_file:
      - .env
    user: postgres
    ports:
      - "5433:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      Analyzemate-network:

  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - /path/to/local/d–∞ta:/root/redis
      - /path/to/local/redis.conf:/usr/local/etc/redis/redis.conf
    env_file:
      - .env
    networks:
      Analyzemate-network:

  app:
    build:
      context: .
    env_file:
      - .env
    container_name: AnalyzeMate_app
    ports:
      - "${APP_PORT}:${APP_PORT}"
    depends_on:
      - db
      - redis
    command: bash -c "while !</dev/tcp/db/5432 || !</dev/tcp/redis/6379; do sleep 1; done; alembic upgrade head & gunicorn main:app --worker-class uvicorn.workers.UvicornWorker --bind=0.0.0.0:8000"
    restart: always
    networks:
      Analyzemate-network:

networks:
  Analyzemate-network:
    name: analyzemate-network