services:
  db:
    image: postgres:16.1
    container_name: db
    env_file:
      - .env
    user: postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5


  app:
    build:
      context: .
    env_file:
      - .env-non-dev
    container_name: AnalyzeMate_app
    ports:
      - 8000:8000
    depends_on:
      - db
    command: bash -c "while !</dev/tcp/db/5432; do sleep 1; done; alembic upgrade head & gunicorn main:app --worker-class uvicorn.workers.UvicornWorker --bind=0.0.0.0:8000"
