"""change pk in candles

Revision ID: 1188061f977f
Revises: 8ed1eeaa51a4
Create Date: 2024-04-26 00:38:03.281278

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1188061f977f'
down_revision: Union[str, None] = '8ed1eeaa51a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('historic_candle',
    sa.Column('open', sa.Float(), nullable=False),
    sa.Column('close', sa.Float(), nullable=False),
    sa.Column('highest', sa.Float(), nullable=False),
    sa.Column('lowest', sa.Float(), nullable=False),
    sa.Column('volume', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(), nullable=False),
    sa.Column('timeframe', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['ticker'], ['securities.ticker'], ),
    sa.PrimaryKeyConstraint('ticker', 'timeframe', 'timestamp')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('historic_candle')
    # ### end Alembic commands ###
