"""Add portfolio, transactions. Fix User, securities, historic candles

Revision ID: 5de3e9cda0d1
Revises: 3160611ad2f5
Create Date: 2024-04-04 21:52:18.096693

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5de3e9cda0d1'
down_revision: Union[str, None] = '3160611ad2f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('historic_candle',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('open', sa.Float(), nullable=False),
    sa.Column('close', sa.Float(), nullable=False),
    sa.Column('highest', sa.Float(), nullable=False),
    sa.Column('lowest', sa.Float(), nullable=False),
    sa.Column('volume', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ticker'], ['securities.ticker'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('portfolio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('balance', sa.Float(), nullable=False),
    sa.Column('owner', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['owner'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transactions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('volume', sa.Integer(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('security', sa.String(), nullable=False),
    sa.Column('portfolio', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['portfolio'], ['portfolio.id'], ),
    sa.ForeignKeyConstraint(['security'], ['securities.ticker'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_constraint('securities_price_history_fkey', 'securities', type_='foreignkey')
    op.drop_table('price_history')
    op.drop_column('securities', 'price_history')
    op.drop_column('securities', 'description')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('securities', sa.Column('price_history', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('securities', sa.Column('description', sa.String(), nullable=True))
    op.create_table('price_history',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('timestamp', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='price_history_pkey')
    )
    op.create_foreign_key('securities_price_history_fkey', 'securities', 'price_history', ['price_history'], ['id'])
    op.drop_table('transactions')
    op.drop_table('portfolio')
    op.drop_table('historic_candle')
    # ### end Alembic commands ###
