"""change pk in candles

Revision ID: 8ed1eeaa51a4
Revises: bce2235e926f
Create Date: 2024-04-26 00:36:33.561100

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8ed1eeaa51a4'
down_revision: Union[str, None] = 'bce2235e926f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("historic_candle")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('historic_candle',
                    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('open', sa.Float(), nullable=False),
                    sa.Column('close', sa.Float(), nullable=False),
                    sa.Column('highest', sa.Float(), nullable=False),
                    sa.Column('lowest', sa.Float(), nullable=False),
                    sa.Column('volume', sa.Integer(), nullable=False),
                    sa.Column('ticker', sa.String(), nullable=False),
                    sa.Column('timeframe', sa.Integer(), nullable=False),
                    sa.Column('timestamp', sa.Float(), nullable=False),
                    sa.ForeignKeyConstraint(['ticker'], ['securities.ticker'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###
