"""add security price

Revision ID: a56fd82904c1
Revises: 1188061f977f
Create Date: 2024-04-26 00:52:35.120352

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a56fd82904c1'
down_revision: Union[str, None] = '1188061f977f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('securities', sa.Column('price', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('securities', 'price')
    # ### end Alembic commands ###
