"""add user notification

Revision ID: abb601e5d226
Revises: dbfa106ea0db
Create Date: 2024-05-15 00:38:15.008167

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'abb601e5d226'
down_revision: Union[str, None] = 'dbfa106ea0db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_notification',
    sa.Column('ticker', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('last_commit', sa.DateTime(), nullable=True),
    sa.Column('open', sa.Float(), nullable=True),
    sa.Column('close', sa.Float(), nullable=True),
    sa.Column('take', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['ticker'], ['securities.ticker'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('ticker', 'user_id')
    )
    op.drop_table('strategies_securities_link')
    op.drop_table('strategies')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('strategies',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('strategies_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('config', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='strategies_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('strategies_securities_link',
    sa.Column('strategy_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('ticker', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('portfolio_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolio.id'], name='strategies_securities_link_portfolio_id_fkey'),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategies.id'], name='strategies_securities_link_strategy_id_fkey'),
    sa.ForeignKeyConstraint(['ticker'], ['securities.ticker'], name='strategies_securities_link_ticker_fkey'),
    sa.PrimaryKeyConstraint('strategy_id', 'ticker', 'portfolio_id', name='strategies_securities_link_pkey')
    )
    op.drop_table('user_notification')
    # ### end Alembic commands ###
