"""timestamp to float

Revision ID: bce2235e926f
Revises: 8ac292250d57
Create Date: 2024-04-24 14:51:26.194290

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bce2235e926f'
down_revision: Union[str, None] = '8ac292250d57'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('historic_candle', 'timestamp')
    op.add_column('historic_candle', sa.Column('timestamp', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('historic_candle', 'timestamp')
    op.add_column('historic_candle', sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###
