"""add security-strategies-link

Revision ID: dbfa106ea0db
Revises: b963b490cda4
Create Date: 2024-05-13 01:22:36.381904

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision: str = 'dbfa106ea0db'
down_revision: Union[str, None] = 'b963b490cda4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('strategies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('config', mssql.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('strategies_securities_link',
    sa.Column('strategy_id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(), nullable=False),
    sa.Column('portfolio_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolio.id'], ),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategies.id'], ),
    sa.ForeignKeyConstraint(['ticker'], ['securities.ticker'], ),
    sa.PrimaryKeyConstraint('strategy_id', 'ticker', 'portfolio_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('strategies_securities_link')
    op.drop_table('strategies')
    # ### end Alembic commands ###
