name: Code Quality
on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: "3.12.2"
    - run: pip install --upgrade pip
    - run: pip install ruff mypy
    - run: ruff check .
    - run: mypy . --exclude alembic
